#!/bin/bash

#################################
# mylog - by tony baldwin       #
# http://tonybaldwin.me         #
# keeping a personal log        #
# released according to GPL v.3 #
#################################

source ~/.mylog.conf

filedate=$(date +%Y%m%d%H%M%S)

cd ~/.mylog

if [[ $1 = r ]]; then
	if [[ $2 ]]; then
		cat $2* | less
	else
		for i in $(ls -Rt *.mylog); do cat $i; done | less
	fi
else
if [[ $1 = h ]]; then
	echo "mylog - opens a new mylog file to edit in $editor.
mylog e filename - opens log entry with filename for editing. Must use full filename.
mylog r - reads all entries (cats all files in the dir, pipes to less)
mylog r yyyymmdd - reads entries from date yyyymmdd. One can specify just yyyymm, or just yyyy, even.
mylog l - lists all mylog entries. Like r, it can be narrowed down with date parameters.
mylog s searchterm - searches for searchterm in my entries.
mylog h - displays this help message.
mylog management system by tony baldwin, http://tonybaldwin.me, released according to GPL v. 3"

else
if [[ $1 = l ]]; then
	if [[ $2 ]]; then
		ls -1t | grep $2
	else
		ls -1t
	fi
else
if [[ $1 = e ]]; then
	$editor $2
else
if [[ $1 = s ]]; then
	grep -iw $2 *

else
	date=`$date`
	echo -e "\n$date\n\nWRITE HERE\n\n--------------" > $filedate.mylog
	$editor $filedate.mylog
fi
fi
fi
fi
fi
exit
