#!/bin/bash

#################################
# mylog - by tony baldwin       #
# http://tonybaldwin.me         #
# keeping a personal log        #
# released according to GPL v.3 #
#################################

filedate=$(date +%Y%m%d%H%M%S)

source  ~/.mylog.conf
cd ~/.mylog

if [[ $1 = r ]]; then
	if [[ $2 ]]; then
		cat $2* | less
	else
		for i in $(ls -Rt *.mylog); do cat $i; done | less
	fi
else
if [[ $1 = h ]]; then
	echo "mylog - opens a new mylog file to edit in your editor.
mylog e filename - opens log entry with filename for editing. Must use full filename.
mylog v filename - opens log entry with filename for viewing. Must use full filename.
mylog r - reads all entries (cats all files in the dir, pipes to less)
mylog r yyyymmdd - reads entries from date yyyymmdd. One can specify just yyyymm, or just yyyy, even.
mylog l - lists all mylog entries. Like r, it can be narrowed down with date parameters.
mylog s searchterm - searches for searchterm in my entries.
mylog h - displays this help message.
mylog management system by tony baldwin, http://tonybaldwin.me, released according to GPL v. 3"

else
if [[ $1 = l ]]; then
	if [[ $2 ]]; then
		ls -1t | grep $2
	else
		ls -1t
	fi
else
if [[ $1 = e ]]; then
	$editor $2
else
if [[ $1 = s ]]; then
	grep -iw $2 *

else
	date=`date`
	echo -e "\n$date\n\nWRITE HERE\n\n-------------------" > $filedate.mylog
	$editor $filedate.mylog
	read -p "Post to my free-haven? (y/n) " post
	if [[ $post = y ]]; then
		echo -e "\nposted with mylog - http://tonyb.us/mylog\n--\n" >> ~/.mylog/$filedate.my
		ud="$(cat ~/.mylog/$filedate.mylog)"
		title="from mylog"
		echo "would you like to crosspost to "
		read -p "statusnet? " snet
		read -p "twitter? " twit
		read -p "facebook? " fb
		read -p "dreamwidth?  " dw
		read -p "livejournal? " lj
		read -p "insanejournal?" ij
		read -p "tumblr? " tum
		read -p "posterous? " pos
		read -p "wordpress? " wp 
		if [[ $(curl --ssl -u $fuser:$fpass -d "status=$ud&title=$title&ljpost_enable=$lj&ijpost_enable=$ij&posterous_enable=$pos&dwpost_enable=$dw&wppost_enable=$wp&tumblr_enable=$tum&facebook_enable=$fb&twitter_enable=$twit&statusnet_enable=$snet&source=mylog.sh" $fsite/api/statuses/update.xml | grep error) ]]; then
			echo "Error!"
			exit
		else 
			echo "Success!"
		read -p "Shall we have a look in your a browser now? (y/n): " op
			if [ $op = "y" ]; then
			xdg-open $fsite/u/$fuser
			fi
		fi
	fi
fi
fi
fi
fi
fi
exit
